package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/jungo-dev/junkit/scaffold"
)

// featureFiles returns the list of files to generate for a new feature.
func featureFiles(data scaffold.FeatureData, migrationSeq string) []scaffold.File {
	dir := filepath.Join(featuresDir, data.Name)

	return []scaffold.File{
		{Path: filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.up.sql", migrationSeq, data.Table)), Template: migrationUpTmpl(strings.ToUpper(data.Table))},
		{Path: filepath.Join(migrationsDir, fmt.Sprintf("%s_%s.down.sql", migrationSeq, data.Table)), Template: migrationDownTmpl},
		{Path: filepath.Join(queriesDir, data.Name+".sql"), Template: queriesTmpl},
		{Path: filepath.Join(dir, "domain", data.Name+".go"), Template: domainTmpl},
		{Path: filepath.Join(dir, "domain", "errors.go"), Template: domainErrorsTmpl},
		{Path: filepath.Join(dir, "repository", data.Name+"_repository.go"), Template: repositoryTmpl},
		{Path: filepath.Join(dir, "service", data.Name+"_service.go"), Template: serviceTmpl},
		{Path: filepath.Join(dir, "service", data.Name+"_service_test.go"), Template: serviceTestTmpl},
		{Path: filepath.Join(dir, "dto", "v1", data.Name+"_dto.go"), Template: dtoTmpl},
		{Path: filepath.Join(dir, "handler", "v1", data.Name+"_handler.go"), Template: handlerTmpl},
		{Path: filepath.Join(dir, "router", "v1", data.Name+"_router.go"), Template: routerTmpl},
		{Path: filepath.Join(dir, "module.go"), Template: moduleTmpl},
	}
}

// migrationUpTmpl builds the up-migration template with tableUpper baked into the
// banner comment, since Go's text/template has no built-in uppercase function.
func migrationUpTmpl(tableUpper string) string {
	return fmt.Sprintf(`-- =============================================================================
-- %s TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS {{.Table}} (`, tableUpper) + `
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    status     SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_{{.Table}}_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_{{.Table}}_created_at ON {{.Table}} (created_at);
CREATE INDEX IF NOT EXISTS idx_{{.Table}}_deleted_at ON {{.Table}} (deleted_at);

-- =============================================================================
-- updated_at trigger
-- =============================================================================

CREATE OR REPLACE FUNCTION f_set_{{.Table}}_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_{{.Table}}_updated_at
    BEFORE UPDATE ON {{.Table}}
    FOR EACH ROW
    EXECUTE FUNCTION f_set_{{.Table}}_updated_at();
`
}

const migrationDownTmpl = `DROP TRIGGER IF EXISTS trg_{{.Table}}_updated_at ON {{.Table}};
DROP FUNCTION IF EXISTS f_set_{{.Table}}_updated_at;
DROP INDEX IF EXISTS idx_{{.Table}}_deleted_at;
DROP INDEX IF EXISTS idx_{{.Table}}_created_at;
DROP TABLE IF EXISTS {{.Table}};
`

const queriesTmpl = `-- name: Create{{.Pascal}} :one
INSERT INTO {{.Table}} (name, status)
VALUES ($1, $2)
RETURNING *;

-- name: Get{{.Pascal}}ByUUID :one
SELECT * FROM {{.Table}} WHERE uuid = $1 AND deleted_at IS NULL;

-- name: List{{.Pascal}}s :many
SELECT * FROM {{.Table}}
WHERE deleted_at IS NULL
  AND (sqlc.arg(search)::text = '' OR name ILIKE '%' || sqlc.arg(search) || '%')
ORDER BY
    CASE WHEN sqlc.arg(sort_order)::text = 'asc' THEN created_at END ASC,
    CASE WHEN sqlc.arg(sort_order)::text = 'desc' OR sqlc.arg(sort_order)::text = '' THEN created_at END DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: Count{{.Pascal}}s :one
SELECT count(*) FROM {{.Table}}
WHERE deleted_at IS NULL
  AND (sqlc.arg(search)::text = '' OR name ILIKE '%' || sqlc.arg(search) || '%');

-- name: Update{{.Pascal}} :one
UPDATE {{.Table}} SET
    name   = COALESCE(sqlc.narg(name), name),
    status = COALESCE(sqlc.narg(status), status)
WHERE uuid = sqlc.arg(uuid) AND deleted_at IS NULL
RETURNING *;

-- name: Delete{{.Pascal}} :execrows
UPDATE {{.Table}} SET deleted_at = now() WHERE uuid = $1 AND deleted_at IS NULL;
`

const domainTmpl = `package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// {{.Pascal}} status constants.
const (
	{{.Pascal}}StatusActive   int16 = 1
	{{.Pascal}}StatusInactive int16 = 2
)

// {{.Pascal}} represents the {{.Name}} entity.
type {{.Pascal}} struct {
	Uuid      uuid.UUID
	Name      string
	Status    int16
	CreatedAt time.Time
	UpdatedAt *time.Time
}

// IsActive checks if the {{.Name}} is active.
func (m *{{.Pascal}}) IsActive() bool {
	return m.Status == {{.Pascal}}StatusActive
}

// Create{{.Pascal}}Input holds data for creating a {{.Name}}.
type Create{{.Pascal}}Input struct {
	Name   string
	Status int16
}

// Update{{.Pascal}}Input holds data for updating a {{.Name}}.
type Update{{.Pascal}}Input struct {
	Name   *string
	Status *int16
}

// {{.Pascal}}ListFilter holds parameters for filtering and paginating {{.Name}}s.
type {{.Pascal}}ListFilter struct {
	Search    string
	Limit     int32
	Offset    int32
	SortOrder string
}

// {{.Pascal}}Repository defines database operations for {{.Name}}s.
type {{.Pascal}}Repository interface {
	Create(ctx context.Context, input Create{{.Pascal}}Input) (*{{.Pascal}}, error)
	GetByUUID(ctx context.Context, id uuid.UUID) (*{{.Pascal}}, error)
	List(ctx context.Context, filter {{.Pascal}}ListFilter) ([]*{{.Pascal}}, int64, error)
	Update(ctx context.Context, id uuid.UUID, input Update{{.Pascal}}Input) (*{{.Pascal}}, error)
	Delete(ctx context.Context, id uuid.UUID) error
}

// {{.Pascal}}Service defines business logic for {{.Name}}s.
type {{.Pascal}}Service interface {
	Create{{.Pascal}}(ctx context.Context, input Create{{.Pascal}}Input) (*{{.Pascal}}, error)
	Get{{.Pascal}}(ctx context.Context, id uuid.UUID) (*{{.Pascal}}, error)
	Get{{.Pascal}}s(ctx context.Context, filter {{.Pascal}}ListFilter) ([]*{{.Pascal}}, int64, error)
	Update{{.Pascal}}(ctx context.Context, id uuid.UUID, input Update{{.Pascal}}Input) (*{{.Pascal}}, error)
	Delete{{.Pascal}}(ctx context.Context, id uuid.UUID) error
}
`

const domainErrorsTmpl = `package domain

import "github.com/jungo-dev/junkit/response"

// Domain errors for the {{.Name}} feature.
var (
	Err{{.Pascal}}NotFound = response.New(response.NotFound, "{{.Name}}_not_found")
)
`

const repositoryTmpl = `package repository

import (
	"context"

	"github.com/google/uuid"

	"github.com/jungo-dev/junkit/database"

	"{{.Module}}/internal/database/sqlc"
	"{{.Module}}/internal/features/{{.Name}}/domain"
)

// {{.Pascal}}Repository implements domain.{{.Pascal}}Repository.
type {{.Pascal}}Repository struct {
	db *database.DB
}

// New{{.Pascal}}Repository creates a {{.Pascal}}Repository backed by db.
func New{{.Pascal}}Repository(db *database.DB) *{{.Pascal}}Repository {
	return &{{.Pascal}}Repository{db: db}
}

// Create implements domain.{{.Pascal}}Repository.
func (r *{{.Pascal}}Repository) Create(ctx context.Context, input domain.Create{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	row, err := sqlc.New(r.db.Executor(ctx)).Create{{.Pascal}}(ctx, sqlc.Create{{.Pascal}}Params{
		Name:   input.Name,
		Status: input.Status,
	})
	if err != nil {
		return nil, err
	}
	return map{{.Pascal}}(row), nil
}

// GetByUUID implements domain.{{.Pascal}}Repository.
func (r *{{.Pascal}}Repository) GetByUUID(ctx context.Context, id uuid.UUID) (*domain.{{.Pascal}}, error) {
	row, err := sqlc.New(r.db.Executor(ctx)).Get{{.Pascal}}ByUUID(ctx, id)
	if err != nil {
		return nil, database.Match(err, map[database.ErrorType]error{
			database.ErrorNotFound: domain.Err{{.Pascal}}NotFound,
		})
	}
	return map{{.Pascal}}(row), nil
}

// List implements domain.{{.Pascal}}Repository, returning a page of {{.Name}}s plus the
// total count matching filter.Search for pagination metadata.
func (r *{{.Pascal}}Repository) List(ctx context.Context, filter domain.{{.Pascal}}ListFilter) ([]*domain.{{.Pascal}}, int64, error) {
	queries := sqlc.New(r.db.Executor(ctx))

	rows, err := queries.List{{.Pascal}}s(ctx, sqlc.List{{.Pascal}}sParams{
		Limit:     filter.Limit,
		Offset:    filter.Offset,
		Search:    filter.Search,
		SortOrder: filter.SortOrder,
	})
	if err != nil {
		return nil, 0, err
	}

	total, err := queries.Count{{.Pascal}}s(ctx, filter.Search)
	if err != nil {
		return nil, 0, err
	}

	items := make([]*domain.{{.Pascal}}, len(rows))
	for i, row := range rows {
		items[i] = map{{.Pascal}}(row)
	}
	return items, total, nil
}

// Update implements domain.{{.Pascal}}Repository.
func (r *{{.Pascal}}Repository) Update(ctx context.Context, id uuid.UUID, input domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	row, err := sqlc.New(r.db.Executor(ctx)).Update{{.Pascal}}(ctx, sqlc.Update{{.Pascal}}Params{
		Uuid:   id,
		Name:   input.Name,
		Status: input.Status,
	})
	if err != nil {
		return nil, database.Match(err, map[database.ErrorType]error{
			database.ErrorNotFound: domain.Err{{.Pascal}}NotFound,
		})
	}
	return map{{.Pascal}}(row), nil
}

// Delete implements domain.{{.Pascal}}Repository. It soft-deletes: the row is kept
// and stamped with deleted_at, and every other query excludes it from then on.
func (r *{{.Pascal}}Repository) Delete(ctx context.Context, id uuid.UUID) error {
	rowsAffected, err := sqlc.New(r.db.Executor(ctx)).Delete{{.Pascal}}(ctx, id)
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return domain.Err{{.Pascal}}NotFound
	}
	return nil
}

// map{{.Pascal}} converts a generated sqlc.{{.Pascal}} row to the domain model.
func map{{.Pascal}}(row sqlc.{{.Pascal}}) *domain.{{.Pascal}} {
	return &domain.{{.Pascal}}{
		Uuid:      row.Uuid,
		Name:      row.Name,
		Status:    row.Status,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
	}
}
`

const serviceTmpl = `package service

import (
	"context"
	"time"

	"github.com/google/uuid"

	"github.com/jungo-dev/junkit/cache"

	"{{.Module}}/internal/features/{{.Name}}/domain"
)

const cacheTTL = 5 * time.Minute

// {{.Pascal}}Service implements domain.{{.Pascal}}Service.
type {{.Pascal}}Service struct {
	repo  domain.{{.Pascal}}Repository
	cache cache.Cache[*domain.{{.Pascal}}]
}

// New{{.Pascal}}Service creates a {{.Pascal}}Service.
func New{{.Pascal}}Service(repo domain.{{.Pascal}}Repository, cache cache.Cache[*domain.{{.Pascal}}]) *{{.Pascal}}Service {
	return &{{.Pascal}}Service{repo: repo, cache: cache}
}

// Create{{.Pascal}} creates a new {{.Name}}.
//
// Flow: persist -> return
func (s *{{.Pascal}}Service) Create{{.Pascal}}(ctx context.Context, input domain.Create{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	return s.repo.Create(ctx, input)
}

// Get{{.Pascal}} returns a {{.Name}} by UUID.
func (s *{{.Pascal}}Service) Get{{.Pascal}}(ctx context.Context, id uuid.UUID) (*domain.{{.Pascal}}, error) {
	return s.cache.GetOrSet(ctx, cacheKey(id), cacheTTL, func() (*domain.{{.Pascal}}, error) {
		return s.repo.GetByUUID(ctx, id)
	})
}

// Get{{.Pascal}}s returns a paginated list of {{.Name}}s.
func (s *{{.Pascal}}Service) Get{{.Pascal}}s(ctx context.Context, filter domain.{{.Pascal}}ListFilter) ([]*domain.{{.Pascal}}, int64, error) {
	return s.repo.List(ctx, filter)
}

// Update{{.Pascal}} updates {{.Name}} information.
//
// Flow: update in DB -> invalidate cache -> return
func (s *{{.Pascal}}Service) Update{{.Pascal}}(ctx context.Context, id uuid.UUID, input domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	updated, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, err
	}
	_ = s.cache.Delete(ctx, cacheKey(id))
	return updated, nil
}

// Delete{{.Pascal}} deletes a {{.Name}} by UUID.
//
// Flow: delete in DB -> invalidate cache
func (s *{{.Pascal}}Service) Delete{{.Pascal}}(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return err
	}
	_ = s.cache.Delete(ctx, cacheKey(id))
	return nil
}

// cacheKey returns the cache key for a {{.Name}} identified by uuid.
func cacheKey(id uuid.UUID) string {
	return "{{.Name}}:" + id.String()
}
`

const serviceTestTmpl = `package service

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/google/uuid"

	"{{.Module}}/internal/features/{{.Name}}/domain"
)

// fake{{.Pascal}}Repository is a hand-written test double for domain.{{.Pascal}}Repository.
// Each Func field defaults to nil; a test that hits an unset one will panic,
// which surfaces unintended calls immediately instead of silently zero-valuing them.
type fake{{.Pascal}}Repository struct {
	CreateFunc    func(ctx context.Context, input domain.Create{{.Pascal}}Input) (*domain.{{.Pascal}}, error)
	GetByUUIDFunc func(ctx context.Context, id uuid.UUID) (*domain.{{.Pascal}}, error)
	ListFunc      func(ctx context.Context, filter domain.{{.Pascal}}ListFilter) ([]*domain.{{.Pascal}}, int64, error)
	UpdateFunc    func(ctx context.Context, id uuid.UUID, input domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error)
	DeleteFunc    func(ctx context.Context, id uuid.UUID) error
}

func (f *fake{{.Pascal}}Repository) Create(ctx context.Context, input domain.Create{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	return f.CreateFunc(ctx, input)
}

func (f *fake{{.Pascal}}Repository) GetByUUID(ctx context.Context, id uuid.UUID) (*domain.{{.Pascal}}, error) {
	return f.GetByUUIDFunc(ctx, id)
}

func (f *fake{{.Pascal}}Repository) List(ctx context.Context, filter domain.{{.Pascal}}ListFilter) ([]*domain.{{.Pascal}}, int64, error) {
	return f.ListFunc(ctx, filter)
}

func (f *fake{{.Pascal}}Repository) Update(ctx context.Context, id uuid.UUID, input domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
	return f.UpdateFunc(ctx, id, input)
}

func (f *fake{{.Pascal}}Repository) Delete(ctx context.Context, id uuid.UUID) error {
	return f.DeleteFunc(ctx, id)
}

// fake{{.Pascal}}Cache is a pass-through cache stub: GetOrSet always calls fetchFn (simulating
// a permanent cache miss), and Delete calls are recorded so tests can assert on invalidation.
type fake{{.Pascal}}Cache struct {
	deletedKeys []string
}

func (f *fake{{.Pascal}}Cache) Get(ctx context.Context, key string) (*domain.{{.Pascal}}, bool) {
	return nil, false
}

func (f *fake{{.Pascal}}Cache) Set(ctx context.Context, key string, value *domain.{{.Pascal}}, ttl time.Duration) error {
	return nil
}

func (f *fake{{.Pascal}}Cache) Delete(ctx context.Context, key string) error {
	f.deletedKeys = append(f.deletedKeys, key)
	return nil
}

func (f *fake{{.Pascal}}Cache) Exists(ctx context.Context, key string) (bool, error) {
	return false, nil
}

func (f *fake{{.Pascal}}Cache) GetOrSet(ctx context.Context, key string, ttl time.Duration, fetchFn func() (*domain.{{.Pascal}}, error)) (*domain.{{.Pascal}}, error) {
	return fetchFn()
}

func (f *fake{{.Pascal}}Cache) Close() error {
	return nil
}

func TestCreate{{.Pascal}}(t *testing.T) {
	want := &domain.{{.Pascal}}{Name: "widget"}
	repo := &fake{{.Pascal}}Repository{
		CreateFunc: func(context.Context, domain.Create{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
			return want, nil
		},
	}
	svc := New{{.Pascal}}Service(repo, &fake{{.Pascal}}Cache{})

	got, err := svc.Create{{.Pascal}}(context.Background(), domain.Create{{.Pascal}}Input{Name: "widget"})
	if err != nil {
		t.Fatalf("Create{{.Pascal}}() error = %v, want nil", err)
	}
	if got != want {
		t.Errorf("Create{{.Pascal}}() = %v, want %v", got, want)
	}
}

func TestGet{{.Pascal}}(t *testing.T) {
	id := uuid.New()
	want := &domain.{{.Pascal}}{Uuid: id}
	repo := &fake{{.Pascal}}Repository{
		GetByUUIDFunc: func(_ context.Context, gotID uuid.UUID) (*domain.{{.Pascal}}, error) {
			if gotID != id {
				t.Errorf("GetByUUID called with %v, want %v", gotID, id)
			}
			return want, nil
		},
	}
	svc := New{{.Pascal}}Service(repo, &fake{{.Pascal}}Cache{})

	got, err := svc.Get{{.Pascal}}(context.Background(), id)
	if err != nil {
		t.Fatalf("Get{{.Pascal}}() error = %v, want nil", err)
	}
	if got != want {
		t.Errorf("Get{{.Pascal}}() = %v, want %v", got, want)
	}
}

func TestGet{{.Pascal}}_RepositoryError(t *testing.T) {
	wantErr := errors.New("not found")
	repo := &fake{{.Pascal}}Repository{
		GetByUUIDFunc: func(context.Context, uuid.UUID) (*domain.{{.Pascal}}, error) { return nil, wantErr },
	}
	svc := New{{.Pascal}}Service(repo, &fake{{.Pascal}}Cache{})

	_, err := svc.Get{{.Pascal}}(context.Background(), uuid.New())
	if !errors.Is(err, wantErr) {
		t.Fatalf("Get{{.Pascal}}() error = %v, want %v", err, wantErr)
	}
}

func TestGet{{.Pascal}}s(t *testing.T) {
	filter := domain.{{.Pascal}}ListFilter{Search: "widget", Limit: 10, SortOrder: "desc"}
	wantItems := []*domain.{{.Pascal}}{ {Name: "widget"} }
	repo := &fake{{.Pascal}}Repository{
		ListFunc: func(_ context.Context, gotFilter domain.{{.Pascal}}ListFilter) ([]*domain.{{.Pascal}}, int64, error) {
			if gotFilter != filter {
				t.Errorf("List called with %+v, want %+v", gotFilter, filter)
			}
			return wantItems, 1, nil
		},
	}
	svc := New{{.Pascal}}Service(repo, &fake{{.Pascal}}Cache{})

	items, total, err := svc.Get{{.Pascal}}s(context.Background(), filter)
	if err != nil {
		t.Fatalf("Get{{.Pascal}}s() error = %v, want nil", err)
	}
	if total != 1 || len(items) != 1 {
		t.Errorf("Get{{.Pascal}}s() = (%v, %d), want (1 item, 1)", items, total)
	}
}

func TestUpdate{{.Pascal}}(t *testing.T) {
	id := uuid.New()
	repo := &fake{{.Pascal}}Repository{
		UpdateFunc: func(_ context.Context, gotID uuid.UUID, _ domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
			return &domain.{{.Pascal}}{Uuid: gotID}, nil
		},
	}
	cache := &fake{{.Pascal}}Cache{}
	svc := New{{.Pascal}}Service(repo, cache)

	if _, err := svc.Update{{.Pascal}}(context.Background(), id, domain.Update{{.Pascal}}Input{}); err != nil {
		t.Fatalf("Update{{.Pascal}}() error = %v, want nil", err)
	}
	if len(cache.deletedKeys) != 1 || cache.deletedKeys[0] != cacheKey(id) {
		t.Errorf("cache.Delete calls = %v, want exactly [%q]", cache.deletedKeys, cacheKey(id))
	}
}

func TestUpdate{{.Pascal}}_DoesNotInvalidateCacheOnError(t *testing.T) {
	wantErr := errors.New("db error")
	repo := &fake{{.Pascal}}Repository{
		UpdateFunc: func(context.Context, uuid.UUID, domain.Update{{.Pascal}}Input) (*domain.{{.Pascal}}, error) {
			return nil, wantErr
		},
	}
	cache := &fake{{.Pascal}}Cache{}
	svc := New{{.Pascal}}Service(repo, cache)

	_, err := svc.Update{{.Pascal}}(context.Background(), uuid.New(), domain.Update{{.Pascal}}Input{})
	if !errors.Is(err, wantErr) {
		t.Fatalf("Update{{.Pascal}}() error = %v, want %v", err, wantErr)
	}
	if len(cache.deletedKeys) != 0 {
		t.Errorf("cache.Delete called %d times, want 0", len(cache.deletedKeys))
	}
}

func TestDelete{{.Pascal}}(t *testing.T) {
	id := uuid.New()
	repo := &fake{{.Pascal}}Repository{
		DeleteFunc: func(context.Context, uuid.UUID) error { return nil },
	}
	cache := &fake{{.Pascal}}Cache{}
	svc := New{{.Pascal}}Service(repo, cache)

	if err := svc.Delete{{.Pascal}}(context.Background(), id); err != nil {
		t.Fatalf("Delete{{.Pascal}}() error = %v, want nil", err)
	}
	if len(cache.deletedKeys) != 1 || cache.deletedKeys[0] != cacheKey(id) {
		t.Errorf("cache.Delete calls = %v, want exactly [%q]", cache.deletedKeys, cacheKey(id))
	}
}

func TestDelete{{.Pascal}}_DoesNotInvalidateCacheOnError(t *testing.T) {
	wantErr := errors.New("not found")
	repo := &fake{{.Pascal}}Repository{
		DeleteFunc: func(context.Context, uuid.UUID) error { return wantErr },
	}
	cache := &fake{{.Pascal}}Cache{}
	svc := New{{.Pascal}}Service(repo, cache)

	if err := svc.Delete{{.Pascal}}(context.Background(), uuid.New()); !errors.Is(err, wantErr) {
		t.Fatalf("Delete{{.Pascal}}() error = %v, want %v", err, wantErr)
	}
	if len(cache.deletedKeys) != 0 {
		t.Errorf("cache.Delete called %d times, want 0", len(cache.deletedKeys))
	}
}
`

const dtoTmpl = `package v1

import (
	"time"

	"github.com/google/uuid"

	"github.com/jungo-dev/junkit/pagination"

	"{{.Module}}/internal/features/{{.Name}}/domain"
)

// {{.Pascal}}UuidParam binds the ":uuid" URI path parameter.
type {{.Pascal}}UuidParam struct {
	Uuid string {{"` + "`" + `"}}uri:"uuid" binding:"required,uuid"{{"` + "`" + `"}}
}

// Create{{.Pascal}}Request is the request body for POST /{{.Table}}.
type Create{{.Pascal}}Request struct {
	Name   string {{"` + "`" + `"}}json:"name" binding:"required,min=2,max=150"{{"` + "`" + `"}}
	Status int16  {{"` + "`" + `"}}json:"status" binding:"omitempty,oneof=1 2"{{"` + "`" + `"}}
}

// ToCreate{{.Pascal}}Input converts Create{{.Pascal}}Request to domain input.
func ToCreate{{.Pascal}}Input(req Create{{.Pascal}}Request) domain.Create{{.Pascal}}Input {
	status := req.Status
	if status == 0 {
		status = domain.{{.Pascal}}StatusActive
	}
	return domain.Create{{.Pascal}}Input{Name: req.Name, Status: status}
}

// Update{{.Pascal}}Request is the request body for PATCH /{{.Table}}/:uuid.
type Update{{.Pascal}}Request struct {
	Name   *string {{"` + "`" + `"}}json:"name" binding:"omitempty,min=2,max=150"{{"` + "`" + `"}}
	Status *int16  {{"` + "`" + `"}}json:"status" binding:"omitempty,oneof=1 2"{{"` + "`" + `"}}
}

// ToUpdate{{.Pascal}}Input converts Update{{.Pascal}}Request to domain input.
func ToUpdate{{.Pascal}}Input(req Update{{.Pascal}}Request) domain.Update{{.Pascal}}Input {
	return domain.Update{{.Pascal}}Input{Name: req.Name, Status: req.Status}
}

// List{{.Pascal}}sRequest binds query parameters for listing {{.Table}}.
type List{{.Pascal}}sRequest struct {
	pagination.Request
}

// ToFilter converts List{{.Pascal}}sRequest to domain filter.
func (r *List{{.Pascal}}sRequest) ToFilter() domain.{{.Pascal}}ListFilter {
	return domain.{{.Pascal}}ListFilter{
		Search:    r.Search,
		Limit:     r.GetLimit(),
		Offset:    r.GetOffset(),
		SortOrder: r.SortOrder,
	}
}

// {{.Pascal}}Response represents the JSON response for a {{.Name}}.
type {{.Pascal}}Response struct {
	Uuid      uuid.UUID  {{"` + "`" + `"}}json:"uuid"{{"` + "`" + `"}}
	Name      string     {{"` + "`" + `"}}json:"name"{{"` + "`" + `"}}
	Status    int16      {{"` + "`" + `"}}json:"status"{{"` + "`" + `"}}
	Active    bool       {{"` + "`" + `"}}json:"active"{{"` + "`" + `"}}
	CreatedAt time.Time  {{"` + "`" + `"}}json:"created_at"{{"` + "`" + `"}}
	UpdatedAt *time.Time {{"` + "`" + `"}}json:"updated_at,omitempty"{{"` + "`" + `"}}
}

// New{{.Pascal}}Response converts domain.{{.Pascal}} to {{.Pascal}}Response.
func New{{.Pascal}}Response(m *domain.{{.Pascal}}) {{.Pascal}}Response {
	return {{.Pascal}}Response{
		Uuid:      m.Uuid,
		Name:      m.Name,
		Status:    m.Status,
		Active:    m.IsActive(),
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
	}
}

// New{{.Pascal}}ResponseList converts a slice of domain.{{.Pascal}} to {{.Pascal}}Response list.
func New{{.Pascal}}ResponseList(items []*domain.{{.Pascal}}) []{{.Pascal}}Response {
	responses := make([]{{.Pascal}}Response, len(items))
	for i, m := range items {
		responses[i] = New{{.Pascal}}Response(m)
	}
	return responses
}
`

const handlerTmpl = `package v1

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"

	"github.com/jungo-dev/junkit/pagination"
	"github.com/jungo-dev/junkit/response"
	"github.com/jungo-dev/junkit/validation"

	"{{.Module}}/internal/features/{{.Name}}/domain"
	v1dto "{{.Module}}/internal/features/{{.Name}}/dto/v1"
)

// {{.Pascal}}Handler adapts HTTP requests to domain.{{.Pascal}}Service calls.
type {{.Pascal}}Handler struct {
	service   domain.{{.Pascal}}Service
	responder response.Responder
	validator *validation.Validator
}

// New{{.Pascal}}Handler creates a {{.Pascal}}Handler.
func New{{.Pascal}}Handler(service domain.{{.Pascal}}Service, responder response.Responder, validator *validation.Validator) *{{.Pascal}}Handler {
	return &{{.Pascal}}Handler{service: service, responder: responder, validator: validator}
}

// Create{{.Pascal}} handles POST /{{.Table}}.
func (h *{{.Pascal}}Handler) Create{{.Pascal}}(ctx *gin.Context) {
	var req v1dto.Create{{.Pascal}}Request
	if err := ctx.ShouldBindJSON(&req); err != nil {
		h.responder.SendWithData(ctx, http.StatusUnprocessableEntity, "validation_error", h.validator.GetValidationErrors(ctx, err))
		return
	}

	item, err := h.service.Create{{.Pascal}}(ctx.Request.Context(), v1dto.ToCreate{{.Pascal}}Input(req))
	if err != nil {
		h.responder.Error(ctx, err)
		return
	}

	h.responder.SendWithData(ctx, http.StatusCreated, "{{.Name}}_created", v1dto.New{{.Pascal}}Response(item))
}

// Get{{.Pascal}} handles GET /{{.Table}}/:uuid.
func (h *{{.Pascal}}Handler) Get{{.Pascal}}(ctx *gin.Context) {
	id, ok := h.parse{{.Pascal}}UUID(ctx)
	if !ok {
		return
	}

	item, err := h.service.Get{{.Pascal}}(ctx.Request.Context(), id)
	if err != nil {
		h.responder.Error(ctx, err)
		return
	}

	h.responder.SendWithData(ctx, http.StatusOK, "{{.Name}}_retrieved", v1dto.New{{.Pascal}}Response(item))
}

// List{{.Pascal}}s handles GET /{{.Table}}.
func (h *{{.Pascal}}Handler) List{{.Pascal}}s(ctx *gin.Context) {
	var req v1dto.List{{.Pascal}}sRequest
	if err := ctx.ShouldBindQuery(&req); err != nil {
		h.responder.SendWithData(ctx, http.StatusUnprocessableEntity, "validation_error", h.validator.GetValidationErrors(ctx, err))
		return
	}
	req.SetDefaults("created_at", "desc")

	items, total, err := h.service.Get{{.Pascal}}s(ctx.Request.Context(), req.ToFilter())
	if err != nil {
		h.responder.Error(ctx, err)
		return
	}

	meta := pagination.NewPagination(req.Page, req.PageSize, total)
	h.responder.Pagination(ctx, http.StatusOK, "{{.Name}}s_listed", v1dto.New{{.Pascal}}ResponseList(items), meta)
}

// Update{{.Pascal}} handles PATCH /{{.Table}}/:uuid.
func (h *{{.Pascal}}Handler) Update{{.Pascal}}(ctx *gin.Context) {
	id, ok := h.parse{{.Pascal}}UUID(ctx)
	if !ok {
		return
	}

	var req v1dto.Update{{.Pascal}}Request
	if err := ctx.ShouldBindJSON(&req); err != nil {
		h.responder.SendWithData(ctx, http.StatusUnprocessableEntity, "validation_error", h.validator.GetValidationErrors(ctx, err))
		return
	}

	item, err := h.service.Update{{.Pascal}}(ctx.Request.Context(), id, v1dto.ToUpdate{{.Pascal}}Input(req))
	if err != nil {
		h.responder.Error(ctx, err)
		return
	}

	h.responder.SendWithData(ctx, http.StatusOK, "{{.Name}}_updated", v1dto.New{{.Pascal}}Response(item))
}

// Delete{{.Pascal}} handles DELETE /{{.Table}}/:uuid.
func (h *{{.Pascal}}Handler) Delete{{.Pascal}}(ctx *gin.Context) {
	id, ok := h.parse{{.Pascal}}UUID(ctx)
	if !ok {
		return
	}

	if err := h.service.Delete{{.Pascal}}(ctx.Request.Context(), id); err != nil {
		h.responder.Error(ctx, err)
		return
	}

	h.responder.Send(ctx, http.StatusOK, "{{.Name}}_deleted")
}

// parse{{.Pascal}}UUID binds and validates the ":uuid" path parameter.
func (h *{{.Pascal}}Handler) parse{{.Pascal}}UUID(ctx *gin.Context) (uuid.UUID, bool) {
	var params v1dto.{{.Pascal}}UuidParam
	if err := ctx.ShouldBindUri(&params); err != nil {
		h.responder.SendWithData(ctx, http.StatusUnprocessableEntity, "validation_error", h.validator.GetValidationErrors(ctx, err))
		return uuid.Nil, false
	}

	id, err := uuid.Parse(params.Uuid)
	if err != nil {
		h.responder.Send(ctx, http.StatusBadRequest, "invalid_uuid")
		return uuid.Nil, false
	}
	return id, true
}
`

const routerTmpl = `package v1

import (
	"github.com/gin-gonic/gin"

	v1handler "{{.Module}}/internal/features/{{.Name}}/handler/v1"
)

// {{.Pascal}}Routes registers the {{.Name}} feature's endpoints under a version group.
type {{.Pascal}}Routes struct {
	handler *v1handler.{{.Pascal}}Handler
}

// New{{.Pascal}}Routes creates a {{.Pascal}}Routes.
func New{{.Pascal}}Routes(handler *v1handler.{{.Pascal}}Handler) *{{.Pascal}}Routes {
	return &{{.Pascal}}Routes{handler: handler}
}

// Version implements router.Versioned, nesting these routes under "/api/v1".
func (r *{{.Pascal}}Routes) Version() string {
	return "v1"
}

// Register implements router.Routes.
func (r *{{.Pascal}}Routes) Register(group *gin.RouterGroup) {
	items := group.Group("/{{.Table}}")

	items.POST("", r.handler.Create{{.Pascal}})
	items.GET("", r.handler.List{{.Pascal}}s)
	items.GET("/:uuid", r.handler.Get{{.Pascal}})
	items.PATCH("/:uuid", r.handler.Update{{.Pascal}})
	items.DELETE("/:uuid", r.handler.Delete{{.Pascal}})
}
`

const moduleTmpl = `package {{.Name}}

import (
	"go.uber.org/fx"

	"github.com/jungo-dev/junkit/cache"
	"github.com/jungo-dev/junkit/i18n"

	"{{.Module}}/internal/features/{{.Name}}/domain"
	v1handler "{{.Module}}/internal/features/{{.Name}}/handler/v1"
	"{{.Module}}/internal/features/{{.Name}}/repository"
	v1route "{{.Module}}/internal/features/{{.Name}}/router/v1"
	"{{.Module}}/internal/features/{{.Name}}/service"
	"{{.Module}}/internal/router"
)

// Module wires the {{.Name}} feature's dependencies into the application's Fx graph.
var Module = fx.Module("{{.Name}}",
	fx.Provide(
		fx.Annotate(
			repository.New{{.Pascal}}Repository,
			fx.As(new(domain.{{.Pascal}}Repository)),
		),
	),
	fx.Provide(func(opts cache.Options) cache.Cache[*domain.{{.Pascal}}] {
		return cache.New[*domain.{{.Pascal}}](opts)
	}),
	fx.Provide(
		fx.Annotate(
			service.New{{.Pascal}}Service,
			fx.As(new(domain.{{.Pascal}}Service)),
		),
	),
	fx.Provide(v1handler.New{{.Pascal}}Handler),
	fx.Provide(
		fx.Annotate(
			v1route.New{{.Pascal}}Routes,
			fx.As(new(router.Routes)),
			fx.ResultTags({{"` + "`" + `"}}group:"routes"{{"` + "`" + `"}}),
		),
	),

	// =============================================================================
	// COMMANDS
	// =============================================================================

	fx.Invoke(registerTranslations),
)

// registerTranslations registers domain-specific translation messages.
func registerTranslations(translator *i18n.Translator) {
	translator.AddTranslations(map[string]map[string]string{
		i18n.LangEN: {
			"{{.Name}}_not_found": "{{.Pascal}} not found",
			"{{.Name}}_created":   "{{.Pascal}} created successfully",
			"{{.Name}}_retrieved": "{{.Pascal}} retrieved successfully",
			"{{.Name}}s_listed":   "{{.Pascal}}s listed successfully",
			"{{.Name}}_updated":   "{{.Pascal}} updated successfully",
			"{{.Name}}_deleted":   "{{.Pascal}} deleted successfully",
		},
	})
}
`
