-- =============================================================================
-- AUTH_TOKENS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS auth_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id        BIGINT NOT NULL,
    family_uuid    UUID NOT NULL,
    type           SMALLINT NOT NULL,
    hash           CHAR(64) NOT NULL,
    ip_address     INET,
    user_agent     TEXT,
    device_id      VARCHAR(100),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    revoked_reason VARCHAR(30),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT uq_auth_tokens_uuid UNIQUE (uuid),
    CONSTRAINT uq_auth_tokens_hash UNIQUE (hash),
    CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_auth_tokens_type CHECK (type IN (1, 2))
);

COMMENT ON COLUMN auth_tokens.type IS '1 = access token, 2 = refresh token';
COMMENT ON COLUMN auth_tokens.hash IS 'SHA-256 hex of the raw token; the raw token is never stored';
COMMENT ON COLUMN auth_tokens.family_uuid IS 'Login session: groups the access/refresh tokens revoked together';
COMMENT ON COLUMN auth_tokens.revoked_reason IS 'logout | refresh | reuse | rotated | admin | user_disabled';

-- Not partial: GetSessionByHash reads a family's latest pair, revoked rows included.
CREATE INDEX IF NOT EXISTS idx_auth_tokens_family ON auth_tokens (family_uuid, type, id DESC);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_device_active ON auth_tokens (user_id, device_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON auth_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_revoked_at ON auth_tokens (revoked_at) WHERE revoked_at IS NOT NULL;

-- =============================================================================
-- updated_at trigger
-- =============================================================================

CREATE OR REPLACE FUNCTION f_set_auth_tokens_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_auth_tokens_updated_at
    BEFORE UPDATE ON auth_tokens
    FOR EACH ROW
    EXECUTE FUNCTION f_set_auth_tokens_updated_at();
