// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const cleanupTokens = `-- name: CleanupTokens :execrows
DELETE FROM auth_tokens
WHERE expires_at < $1
   OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

func (q *Queries) CleanupTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :execrows
UPDATE auth_tokens
SET revoked_at = now(), revoked_reason = 'refresh'
WHERE hash = $1 AND type = 2 AND revoked_at IS NULL AND expires_at > now()
`

// Zero rows means the token was already used or expired.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshToken, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createLoginSession = `-- name: CreateLoginSession :one
SELECT s.action::text                                                               AS action,
       s.family_uuid::uuid                                                          AS family_uuid,
       COALESCE(s.old_family_uuid, '00000000-0000-0000-0000-000000000000')::uuid    AS old_family_uuid
FROM f_auth_login_session(
    $1::bigint,
    $2::text,
    $3::inet,
    $4::text,
    $5::text,
    $6::timestamptz,
    $7::text,
    $8::timestamptz,
    $9::uuid
) AS s(action, family_uuid, old_family_uuid)
`

type CreateLoginSessionParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	DeviceID         *string     `db:"device_id" json:"device_id"`
	IpAddress        *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent        *string     `db:"user_agent" json:"user_agent"`
	AccessHash       string      `db:"access_hash" json:"access_hash"`
	AccessExpiresAt  time.Time   `db:"access_expires_at" json:"access_expires_at"`
	RefreshHash      string      `db:"refresh_hash" json:"refresh_hash"`
	RefreshExpiresAt time.Time   `db:"refresh_expires_at" json:"refresh_expires_at"`
	NewFamilyUuid    uuid.UUID   `db:"new_family_uuid" json:"new_family_uuid"`
}

type CreateLoginSessionRow struct {
	Action        string    `db:"action" json:"action"`
	FamilyUuid    uuid.UUID `db:"family_uuid" json:"family_uuid"`
	OldFamilyUuid uuid.UUID `db:"old_family_uuid" json:"old_family_uuid"`
}

// old_family_uuid is uuid.Nil when no session existed.
func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) (CreateLoginSessionRow, error) {
	row := q.db.QueryRow(ctx, createLoginSession,
		arg.UserID,
		arg.DeviceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AccessHash,
		arg.AccessExpiresAt,
		arg.RefreshHash,
		arg.RefreshExpiresAt,
		arg.NewFamilyUuid,
	)
	var i CreateLoginSessionRow
	err := row.Scan(&i.Action, &i.FamilyUuid, &i.OldFamilyUuid)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
WITH token AS (
    SELECT t.family_uuid, t.user_id FROM auth_tokens t WHERE t.hash = $1
),
access_token AS (
    SELECT a.id, a.uuid, a.user_id, a.family_uuid, a.type, a.hash, a.ip_address, a.user_agent, a.device_id, a.expires_at, a.revoked_at, a.revoked_reason, a.created_at, a.updated_at FROM auth_tokens a
    WHERE a.family_uuid = (SELECT family_uuid FROM token) AND a.type = 1
    ORDER BY a.id DESC LIMIT 1
),
refresh_token AS (
    SELECT r.id, r.uuid, r.user_id, r.family_uuid, r.type, r.hash, r.ip_address, r.user_agent, r.device_id, r.expires_at, r.revoked_at, r.revoked_reason, r.created_at, r.updated_at FROM auth_tokens r
    WHERE r.family_uuid = (SELECT family_uuid FROM token) AND r.type = 2
    ORDER BY r.id DESC LIMIT 1
)
SELECT
    u.id                 AS user_id,
    u.uuid               AS user_uuid,
    u.email,
    u.first_name,
    u.last_name,
    u.avatar_url,
    u.status             AS user_status,
    tk.family_uuid,
    r.ip_address,
    r.user_agent,
    r.device_id,
    (SELECT min(f.created_at) FROM auth_tokens f WHERE f.family_uuid = tk.family_uuid)::timestamptz AS session_created_at,
    a.uuid               AS access_uuid,
    a.hash               AS access_hash,
    a.expires_at         AS access_expires_at,
    a.revoked_at         AS access_revoked_at,
    r.uuid               AS refresh_uuid,
    r.hash               AS refresh_hash,
    r.expires_at         AS refresh_expires_at,
    r.revoked_at         AS refresh_revoked_at
FROM token tk
JOIN users u ON u.id = tk.user_id AND u.deleted_at IS NULL
JOIN access_token a ON true
JOIN refresh_token r ON true
`

type GetSessionByHashRow struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	UserUuid         uuid.UUID   `db:"user_uuid" json:"user_uuid"`
	Email            string      `db:"email" json:"email"`
	FirstName        string      `db:"first_name" json:"first_name"`
	LastName         string      `db:"last_name" json:"last_name"`
	AvatarUrl        *string     `db:"avatar_url" json:"avatar_url"`
	UserStatus       int16       `db:"user_status" json:"user_status"`
	FamilyUuid       uuid.UUID   `db:"family_uuid" json:"family_uuid"`
	IpAddress        *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent        *string     `db:"user_agent" json:"user_agent"`
	DeviceID         *string     `db:"device_id" json:"device_id"`
	SessionCreatedAt time.Time   `db:"session_created_at" json:"session_created_at"`
	AccessUuid       uuid.UUID   `db:"access_uuid" json:"access_uuid"`
	AccessHash       string      `db:"access_hash" json:"access_hash"`
	AccessExpiresAt  time.Time   `db:"access_expires_at" json:"access_expires_at"`
	AccessRevokedAt  *time.Time  `db:"access_revoked_at" json:"access_revoked_at"`
	RefreshUuid      uuid.UUID   `db:"refresh_uuid" json:"refresh_uuid"`
	RefreshHash      string      `db:"refresh_hash" json:"refresh_hash"`
	RefreshExpiresAt time.Time   `db:"refresh_expires_at" json:"refresh_expires_at"`
	RefreshRevokedAt *time.Time  `db:"refresh_revoked_at" json:"refresh_revoked_at"`
}

// Any token hash of a family -> its user and latest token pair.
func (q *Queries) GetSessionByHash(ctx context.Context, hash string) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, hash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.UserStatus,
		&i.FamilyUuid,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceID,
		&i.SessionCreatedAt,
		&i.AccessUuid,
		&i.AccessHash,
		&i.AccessExpiresAt,
		&i.AccessRevokedAt,
		&i.RefreshUuid,
		&i.RefreshHash,
		&i.RefreshExpiresAt,
		&i.RefreshRevokedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT t.uuid, t.user_id, u.uuid AS user_uuid, u.status AS user_status, t.family_uuid, t.type,
       t.device_id, t.expires_at, t.revoked_at, t.revoked_reason
FROM auth_tokens t
JOIN users u ON u.id = t.user_id AND u.deleted_at IS NULL
WHERE t.hash = $1
`

type GetTokenByHashRow struct {
	Uuid          uuid.UUID  `db:"uuid" json:"uuid"`
	UserID        int64      `db:"user_id" json:"user_id"`
	UserUuid      uuid.UUID  `db:"user_uuid" json:"user_uuid"`
	UserStatus    int16      `db:"user_status" json:"user_status"`
	FamilyUuid    uuid.UUID  `db:"family_uuid" json:"family_uuid"`
	Type          int16      `db:"type" json:"type"`
	DeviceID      *string    `db:"device_id" json:"device_id"`
	ExpiresAt     time.Time  `db:"expires_at" json:"expires_at"`
	RevokedAt     *time.Time `db:"revoked_at" json:"revoked_at"`
	RevokedReason *string    `db:"revoked_reason" json:"revoked_reason"`
}

func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (GetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, hash)
	var i GetTokenByHashRow
	err := row.Scan(
		&i.Uuid,
		&i.UserID,
		&i.UserUuid,
		&i.UserStatus,
		&i.FamilyUuid,
		&i.Type,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const issueTokenPair = `-- name: IssueTokenPair :exec
INSERT INTO auth_tokens (user_id, family_uuid, type, hash, expires_at, ip_address, user_agent, device_id)
VALUES
    ($1, $2, 1, $3, $4,
     $5, $6, $7),
    ($1, $2, 2, $8, $9,
     $5, $6, $7)
`

type IssueTokenPairParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	FamilyUuid       uuid.UUID   `db:"family_uuid" json:"family_uuid"`
	AccessHash       string      `db:"access_hash" json:"access_hash"`
	AccessExpiresAt  time.Time   `db:"access_expires_at" json:"access_expires_at"`
	IpAddress        *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent        *string     `db:"user_agent" json:"user_agent"`
	DeviceID         *string     `db:"device_id" json:"device_id"`
	RefreshHash      string      `db:"refresh_hash" json:"refresh_hash"`
	RefreshExpiresAt time.Time   `db:"refresh_expires_at" json:"refresh_expires_at"`
}

func (q *Queries) IssueTokenPair(ctx context.Context, arg IssueTokenPairParams) error {
	_, err := q.db.Exec(ctx, issueTokenPair,
		arg.UserID,
		arg.FamilyUuid,
		arg.AccessHash,
		arg.AccessExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceID,
		arg.RefreshHash,
		arg.RefreshExpiresAt,
	)
	return err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT family_uuid, ip_address, user_agent, device_id, created_at, updated_at, expires_at
FROM auth_tokens
WHERE user_id = $1 AND type = 2 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

type ListActiveSessionsRow struct {
	FamilyUuid uuid.UUID   `db:"family_uuid" json:"family_uuid"`
	IpAddress  *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent  *string     `db:"user_agent" json:"user_agent"`
	DeviceID   *string     `db:"device_id" json:"device_id"`
	CreatedAt  time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time  `db:"updated_at" json:"updated_at"`
	ExpiresAt  time.Time   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, userID int64) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.FamilyUuid,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllForUser = `-- name: RevokeAllForUser :many
UPDATE auth_tokens t
SET revoked_at = now(), revoked_reason = $1
FROM users u
WHERE u.id = t.user_id AND u.uuid = $2 AND t.revoked_at IS NULL
RETURNING t.family_uuid
`

type RevokeAllForUserParams struct {
	Reason   *string   `db:"reason" json:"reason"`
	UserUuid uuid.UUID `db:"user_uuid" json:"user_uuid"`
}

func (q *Queries) RevokeAllForUser(ctx context.Context, arg RevokeAllForUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllForUser, arg.Reason, arg.UserUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var family_uuid uuid.UUID
		if err := rows.Scan(&family_uuid); err != nil {
			return nil, err
		}
		items = append(items, family_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFamily = `-- name: RevokeFamily :execrows
UPDATE auth_tokens
SET revoked_at = now(), revoked_reason = $1
WHERE family_uuid = $2 AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	Reason     *string   `db:"reason" json:"reason"`
	FamilyUuid uuid.UUID `db:"family_uuid" json:"family_uuid"`
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeFamily, arg.Reason, arg.FamilyUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
