// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           int64      `json:"id"`
	Uuid         uuid.UUID  `json:"uuid"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	PhoneNumber  *string    `json:"phone_number"`
	AvatarUrl    *string    `json:"avatar_url"`
	Status       int16      `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
