// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuthToken struct {
	ID     int64     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	UserID int64     `db:"user_id" json:"user_id"`
	// Login session: groups the access/refresh tokens revoked together
	FamilyUuid uuid.UUID `db:"family_uuid" json:"family_uuid"`
	// 1 = access token, 2 = refresh token
	Type int16 `db:"type" json:"type"`
	// SHA-256 hex of the raw token; the raw token is never stored
	Hash      string      `db:"hash" json:"hash"`
	IpAddress *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent *string     `db:"user_agent" json:"user_agent"`
	DeviceID  *string     `db:"device_id" json:"device_id"`
	ExpiresAt time.Time   `db:"expires_at" json:"expires_at"`
	RevokedAt *time.Time  `db:"revoked_at" json:"revoked_at"`
	// logout | refresh | reuse | rotated | admin | user_disabled
	RevokedReason *string    `db:"revoked_reason" json:"revoked_reason"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     *time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int64      `db:"id" json:"id"`
	Uuid         uuid.UUID  `db:"uuid" json:"uuid"`
	Email        string     `db:"email" json:"email"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	FirstName    string     `db:"first_name" json:"first_name"`
	LastName     string     `db:"last_name" json:"last_name"`
	PhoneNumber  *string    `db:"phone_number" json:"phone_number"`
	AvatarUrl    *string    `db:"avatar_url" json:"avatar_url"`
	Status       int16      `db:"status" json:"status"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
}
